### ISSUE TITLE
[BUG] ValueError in aCompCor

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep#276]
Running ds011
```
nipypecli crash /scratch/03843/crn_plab/fmriprep-ohbm-2/work/ds000011_R2.0.1/out/log/crash-20161215-131711-crn_plab-aCompCor.a4-a96c4457-b951-4f01-ab20-106caa44ba90.pklz


File: /scratch/03843/crn_plab/fmriprep-ohbm-2/work/ds000011_R2.0.1/out/log/crash-20161215-131711-crn_plab-aCompCor.a4-a96c4457-b951-4f01-ab20-106caa44ba90.pklz
Node: workflow_enumerator.09.ConfoundDiscoverer.aCompCor.a4
Working directory: /scratch/03843/crn_plab/fmriprep-ohbm-2/work/ds000011_R2.0.1/work/workflow_enumerator/09/ConfoundDiscoverer/_epi_..scratch..03843..crn_plab..fmriprep-ohbm-2..ds000011_R2.0.1..sub-09..func..sub-09_task-Singletaskweatherprediction_run-02_bold.nii.gz/aCompCor


Node inputs:

components_file = acompcor.tsv
generate_report = True
header = aCompCor
ignore_exception = False
mask_file = /scratch/03843/crn_plab/fmriprep-ohbm-2/work/ds000011_R2.0.1/work/workflow_enumerator/09/ConfoundDiscoverer/_epi_..scratch..03843..crn_plab..fmriprep-ohbm-2..ds000011_R2.0.1..sub-09..func..sub-09_task-Singletaskweatherprediction_run-02_bold.nii.gz/combine_rois/logical_or.nii.gz
num_components = 6
out_report = report.html
realigned_file = /scratch/03843/crn_plab/fmriprep-ohbm-2/work/ds000011_R2.0.1/work/workflow_enumerator/09/EPI_HMC/_epi_..scratch..03843..crn_plab..fmriprep-ohbm-2..ds000011_R2.0.1..sub-09..func..sub-09_task-Singletaskweatherprediction_run-02_bold.nii.gz/EPI_hmc/sub-09_task-Singletaskweatherprediction_run-02_bold_mcf.nii.gz
regress_poly_degree = 1
use_regress_poly = True



Traceback: 
Traceback (most recent call last):
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 367, in run
    self._run_interface()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 477, in _run_interface
    self._result = self._run_command(execute)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/pipeline/engine/nodes.py", line 607, in _run_command
    result = self._interface.run()
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/interfaces/base.py", line 1085, in run
    runtime = self._run_wrapper(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/interfaces/base.py", line 1033, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/niworkflows-0.0.4a0-py2.7.egg/niworkflows/common/report.py", line 45, in _run_interface
    ReportCapableInterface, self)._run_interface(runtime)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/nipype-0.13.0_gff36588.dev-py2.7.egg/nipype/algorithms/confounds.py", line 361, in _run_interface
    u, _, _ = linalg.svd(M, full_matrices=False)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 112, in svd
    compute_uv=compute_uv, full_matrices=full_matrices)
  File "/work/01329/poldrack/lonestar/software_lonestar5/crn-agave/anaconda/lib/python2.7/site-packages/scipy/linalg/lapack.py", line 470, in _compute_lwork
    wi = routine(*args, **kwargs)
ValueError: On entry to DGESDD parameter number 10 had an illegal value
Interface ACompCorRPT failed to run. 
```

**Comment by shoshber** [comment]
I've got this in DS102 too

**Comment by rwblair** [comment]
ds107 as well sub-01_task-onebacktask_run-02,  sub-45_task-oneback_run-02

**Comment by oesteban** [comment]
Some bad values are sneaking into the mask

**Comment by oesteban** [comment]
Happening in ds115 and ds119 too.

**Comment by oesteban** [comment]
One subject on ds116.

**Comment by chrisfilo** [comment]
Many of these errors were caused by coregistration issues (hopefully) solved in #294. Some could be related to #296.

**Comment by shoshber** [comment]
After fixing the coregistration issues there is only one error, which turns out to be due to the epi file looking like this: 

![epi](https://cloud.githubusercontent.com/assets/1402948/21880368/726df99e-d853-11e6-8cac-82e93e198844.png)

**Comment by chrisfilo** [comment]
This is the same subject as reported in https://github.com/poldracklab/fmriprep/issues/291.

If you can confirm that this is the only case among the tested datasets we can close this issue.

**Comment by oesteban** [comment]
I don't think this is still happening. I'll close it and then reopen if we see it again.
